name: 'Terraform: verifications'
run-name: "Verifying Terraform code [PR-${{github.event.pull_request.number}}][SHA: ${{ github.event.pull_request.head.sha}}]" 
on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - '**.tf'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-clean-comments

  terraform-steps:
    runs-on: ubuntu-latest
    needs: [ setup ]
    strategy:
      fail-fast: false
      matrix:
        environment: ['stage', 'production']
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Configure required access
        uses: ./.github/actions/setup-creds
        with:
          github: ${{ secrets.GH_TOKEN }}
          gcloud: ${{ secrets.GCS_JSON }}

      - name: Test action
        uses: SolalVall/action-terraform@main
        with:
          artifact_workflow: false
          directory: terraform/${{ matrix.environment }}
          tf_version: 1.4.6
          tf_init: true
          tf_lint: true
          tf_plan: true
          exec_in_parallel: true
        env:
          DYNATRACE_ENV_URL: ${{ secrets[format('DYNATRACE_{0}_ENV_URL', matrix.environment)] }}
          DYNATRACE_API_TOKEN: ${{ secrets[format('DYNATRACE_{0}_API_TOKEN', matrix.environment)] }}
